### ISSUE TITLE
Botão após pesquisa pega o valor padrão 

### ISSUE THREAD

**Issue by matheusgnreis** [ecomclub/search-engine#2]
Ao inves de pegar o nome do botão setado no widget de produto, ele busca o valor padrão

**Comment by leomp12** [comment]
Não entendi, mas de qualquer forma acho que este issue seria pro https://github.com/ecomclub/widget-search (busca instantânea no cabeçalho) ou https://github.com/ecomclub/widget-search-engine (página de busca)
